services:
  axonserver: #<.>
    image: 'axoniq/axonserver:2024.1.2'  # <.>
    environment: # <.>
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
      - AXONIQ_LICENSE=/axonserver/axoniq.license
    ports: # <.>
      - '8024:8024'  # <.>
      - '8124:8124'  # <.>